platform :ios, '10.0'

target 'GXAudioPlay_Example' do
  use_frameworks!
  
  pod 'GXAudioPlay', :path => '../'
  pod 'GGXSwiftExtension'
#  target 'GXAudioPlay_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end
